config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :start_date, :end_date, presence: true
  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "は今日以降の日付にしてください")
    end
    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "は今日以降の日付にしてください")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(:start_date)
    @counter = Task.where("start_date >= ?",Date.today).count
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params.require(:task).permit(:title,:start_date,:end_date,:all_day,:memo))
    if @task.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :tasks
    else
      render "new"
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:title,:start_date,:end_date,:all_day,:memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :tasks
    else
      render "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="reset">
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <div class="content">
      <%= yield %>
    </div>
      <footer>
        <h1>現在の日時は：<%= Date.today.to_s(:date_jp) %>
        <% if @counter %>
          <span class="task_sum">スケジュール合計：<%= @counter %></span>
        <% end %>
        </h1>
      </footer>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/edit.html.erb
<h2>スケジュール編集</h2>

<%= render "shared/error", obj:@task %>

<%= form_with model:@task do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title%></td>
    </tr>
    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, "終了日"%></th>
      <td><%= f.date_field :end_date %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日"%></th>
      <td>
        <%= f.check_box :all_day %>
        <p>終日の場合はチェックを入れます</p>
      </td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ"%></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>
  <%= f.submit "スケジュールの編集を完了する" %>
<% end %>
<ul>
  <li><%= link_to "スケジュール一覧に戻る", tasks_path %></li>
</ul>

app/views/tasks/index.html.erb
<h2>スケジュール一覧</h2>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.start_date.to_s(:date_jp) %></td>
        <td><%= task.end_date.to_s(:date_jp) %></td>
        <td>
          <% if task.all_day %>◯<% end %>
        </td>
        <td><%= task.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "確認", task %></td>
        <td><%= link_to "編集", edit_task_path(task) %></td>
        <td><%= link_to "削除", task, method: :delete, data:{confirm: "本当に削除しますか？"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul>
  <li><%= link_to "スケジュール新規登録", new_task_path %></li>
</ul>

app/views/tasks/new.html.erb
<h2>スケジュール新規作成</h2>

<%= render "shared/error", obj:@task %>

<%= form_with model:@task do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title%></td>
    </tr>
    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, "終了日"%></th>
      <td><%= f.date_field :end_date %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日"%></th>
      <td>
        <%= f.check_box :all_day %>
        <p>終日の場合はチェックを入れます</p>
      </td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ"%></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>
  <%= f.submit "スケジュールを新規登録する" %>
<% end %>
<ul>
  <li><%= link_to "スケジュール一覧に戻る", tasks_path %></li>
</ul>

app/views/tasks/show.html.erb
<h2>スケジュール詳細</h2>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @task.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @task.start_date %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @task.end_date %></td>
  </tr>
  <tr>
    <th>終日</th>
      <td>
      <% if @task.all_day %>◯<% end %>
      </td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @task.memo %></td>
  </tr>
</table>
<ul>
  <li><%= link_to "スケジュール一覧に戻る", tasks_path %></li>
  <li><%= link_to "スケジュールを編集する", edit_task_path(@task) %></li>
  <li><%= link_to "スケジュールを削除する", task_path, method: :delete, data:{confirm: "本当に削除しますか？"}%></li>
</ul>